base.url=https://automationintesting.online
admin.url=https://automationintesting.online/admin
api.base.url=https://automationintesting.online/api
admin.username=admin
admin.password=password
browser=chrome
browser.size=1920x1080
timeout=10000